### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by CodeFanaticX** [Anonym0ose/JitDumper#7]
I'm trying to load the exe protected with AGILE.Net.
Am I doing, correct? or what should I do first before I use this dumper?
```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'file:///....' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at JitDumper.Program.Main(String[] args) in \JitDumper-master\JitDumper\Program.cs:line 48
```

**Comment by Knakiri** [comment]
check your target .net framework version and compile jitdumper exactly same version.
